"""Extension for PalmSens MethodSCRIPT export."""

from __future__ import annotations

import math
from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal
from enum import StrEnum
from pathlib import Path

from aurora_unicycler import _core, _utils


class PalmSensDevice(StrEnum):
    """Supported PalmSens MethodSCRIPT target devices."""

    EMSTAT4_HR = "emstat4_hr"
    EMSTAT4_LR = "emstat4_lr"
    NEXUS = "nexus"


@dataclass(frozen=True)
class MeasurementVariable:
    """A PalmSens MethodSCRIPT measurement variable."""

    var_type: str
    name: str


@dataclass(frozen=True)
class PalmSensProfile:
    """Device-specific MethodSCRIPT capabilities used by the exporter."""

    device: PalmSensDevice
    display_name: str
    min_voltage_v: float
    max_voltage_v: float
    max_abs_current_ma: float
    max_peis_amplitude_v: float
    max_peis_frequency_hz: float
    max_geis_frequency_hz: float
    supports_geis: bool
    measurement_variables: tuple[MeasurementVariable, ...]


EMSTAT4_VARIABLES = (
    MeasurementVariable("ab", "potential"),
    MeasurementVariable("ac", "potential_ce"),
    MeasurementVariable("ae", "potential_re"),
    MeasurementVariable("ag", "potential_we_vs_ce"),
    MeasurementVariable("as", "potential_ain0"),
    MeasurementVariable("ba", "current"),
)

NEXUS_VARIABLES = (
    MeasurementVariable("ab", "potential"),
    MeasurementVariable("ac", "potential_ce"),
    MeasurementVariable("ag", "potential_we_vs_ce"),
    MeasurementVariable("as", "potential_ain0"),
    MeasurementVariable("ah", "potential_s2_vs_re"),
    MeasurementVariable("ai", "potential_se_vs_s2"),
    MeasurementVariable("ba", "current"),
    MeasurementVariable("bb", "current_bipot"),
    MeasurementVariable("ed", "temperature"),
    MeasurementVariable("ef", "temperature_board"),
)

PALMSENS_PROFILES: dict[PalmSensDevice, PalmSensProfile] = {
    PalmSensDevice.EMSTAT4_HR: PalmSensProfile(
        device=PalmSensDevice.EMSTAT4_HR,
        display_name="EmStat4 HR",
        min_voltage_v=-6.0,
        max_voltage_v=6.0,
        max_abs_current_ma=200.0,
        max_peis_amplitude_v=0.9,
        max_peis_frequency_hz=200_000.0,
        max_geis_frequency_hz=200_000.0,
        supports_geis=True,
        measurement_variables=EMSTAT4_VARIABLES,
    ),
    PalmSensDevice.EMSTAT4_LR: PalmSensProfile(
        device=PalmSensDevice.EMSTAT4_LR,
        display_name="EmStat4 LR",
        min_voltage_v=-3.0,
        max_voltage_v=3.0,
        max_abs_current_ma=30.0,
        max_peis_amplitude_v=0.9,
        max_peis_frequency_hz=200_000.0,
        max_geis_frequency_hz=200_000.0,
        supports_geis=True,
        measurement_variables=EMSTAT4_VARIABLES,
    ),
    PalmSensDevice.NEXUS: PalmSensProfile(
        device=PalmSensDevice.NEXUS,
        display_name="Nexus",
        min_voltage_v=-10.0,
        max_voltage_v=10.0,
        max_abs_current_ma=1000.0,
        max_peis_amplitude_v=0.3,
        max_peis_frequency_hz=1_000_000.0,
        max_geis_frequency_hz=200_000.0,
        supports_geis=True,
        measurement_variables=NEXUS_VARIABLES,
    ),
}


class _Renderer:
    """Render a normalized protocol to MethodSCRIPT lines."""

    def __init__(  # noqa: PLR0913
        self,
        protocol: _core.BaseProtocol,
        profile: PalmSensProfile,
        channel: int,
        scan_step_voltage_v: float | None,
        additional_measurements: tuple[str, ...],
    ) -> None:
        self.protocol = protocol
        self.profile = profile
        self.channel = channel
        self.scan_step_voltage_v = scan_step_voltage_v
        self.additional_measurements = additional_measurements
        self.loop_count = 0

    def render(self) -> list[str]:
        """Render the full MethodSCRIPT."""
        return [
            "e",
            "# Generated by aurora-unicycler",
            f"# PalmSens target: {self.profile.display_name}",
            *self._core_var_declarations(),
            *self._extra_var_declarations(),
            f"set_pgstat_chan {self.channel}",
            "timer_start",
            *self._render_range(0, len(self.protocol.method)),
            "on_finished:",
            "cell_off",
            "",
            "",
        ]

    def _core_var_declarations(self) -> list[str]:
        vars_to_declare = ["t"]
        for step in self.protocol.method:
            if isinstance(step, _core.OpenCircuitVoltage):
                vars_to_declare.append("p")
            elif isinstance(step, _core.ConstantCurrent | _core.ConstantVoltage | _core.VoltageScan):
                vars_to_declare.extend(("p", "i"))
            elif isinstance(step, _core.ImpedanceSpectroscopy):
                vars_to_declare.extend(("f", "z_real", "z_imag"))
                if not step.dc_vs_ocv:
                    vars_to_declare.extend(("e_ac", "e_dc", "i_ac", "i_dc"))
                if step.dc_vs_ocv and step.amplitude_V is not None:
                    vars_to_declare.extend(("ocp1", "v_ocp1"))
        return [f"var {var}" for var in dict.fromkeys(vars_to_declare)]

    def _extra_var_declarations(self) -> list[str]:
        return [
            f"var {self._var_name(var.var_type)}"
            for var in self._additional_measurement_variables()
        ]

    def _render_range(self, start: int, end: int) -> list[str]:
        lines: list[str] = []
        i = start
        while i < end:
            loop_end = self._find_loop_for_start(i, end)
            if loop_end is not None:
                self.loop_count += 1
                counter = f"loop_{self.loop_count}"
                loop_step = self.protocol.method[loop_end]
                assert isinstance(loop_step, _core.Loop)  # noqa: S101
                lines.extend(
                    [
                        f"var {counter}",
                        f"store_var {counter} 0i aa",
                        f"loop {counter} < {loop_step.cycle_count}i",
                        *self._indent(self._render_range(i, loop_end)),
                        f"add_var {counter} 1i",
                        "endloop",
                    ],
                )
                i = loop_end + 1
                continue
            step = self.protocol.method[i]
            if isinstance(step, _core.Loop):
                msg = "PalmSens exporter cannot render this loop layout as structured MethodSCRIPT."
                raise TypeError(msg)
            lines.extend(self._render_step(step))
            i += 1
        return lines

    def _find_loop_for_start(self, start: int, end: int) -> int | None:
        matches = []
        for i in range(start + 1, end):
            step = self.protocol.method[i]
            if isinstance(step, _core.Loop) and step.loop_to == start + 1:
                matches.append(i)
        if len(matches) > 1:
            msg = "PalmSens exporter does not support multiple loops with the same start step."
            raise ValueError(msg)
        return matches[0] if matches else None

    def _render_step(self, step: _core.AnyTechnique) -> list[str]:
        match step:
            case _core.OpenCircuitVoltage():
                return self._render_ocv(step)
            case _core.ConstantCurrent():
                return self._render_cc(step)
            case _core.ConstantVoltage():
                return self._render_cv(step)
            case _core.VoltageScan():
                return self._render_lsv(step)
            case _core.ImpedanceSpectroscopy():
                return self._render_eis(step)
            case _:
                msg = f"to_palmsens_methodscript() does not support step type: {step.step}"
                raise NotImplementedError(msg)

    def _render_ocv(self, step: _core.OpenCircuitVoltage) -> list[str]:
        return [
            "# Open circuit voltage",
            "cell_off",
            f"# Measure OCV every {self._ms_float(self.protocol.record.time_s)} s "
            f"for {self._ms_float(step.until_time_s)} s.",
            self._measurement_loop(
                self._command_with_optional_args(
                    f"meas_loop_ocp p {self._ms_float(self.protocol.record.time_s)} "
                    f"{self._ms_float(step.until_time_s)}",
                    self._add_meas_args({"ab"}),
                    "time(t)",
                ),
                primary_vars=("p",),
                extra_vars=self._extra_measurement_variables({"ab"}),
            ),
        ]

    def _render_cc(self, step: _core.ConstantCurrent) -> list[str]:
        current_ma = self._step_current_ma(step)
        run_time_s = step.until_time_s or self._fallback_runtime_s()
        return [
            "# Constant current",
            "cell_off",
            "set_pgstat_mode 6",
            f"# Apply {self._ms_float(current_ma / 1000)} A and measure every "
            f"{self._ms_float(self.protocol.record.time_s)} s for up to "
            f"{self._ms_float(run_time_s)} s.",
            f"set_range db {self._ms_float(abs(current_ma) / 1000)}",
            f"set_i {self._ms_float(current_ma / 1000)}",
            "cell_on",
            self._measurement_loop(
                self._command_with_optional_args(
                    f"meas_loop_cp p i {self._ms_float(current_ma / 1000)} "
                    f"{self._ms_float(self.protocol.record.time_s)} "
                    f"{self._ms_float(run_time_s)}",
                    self._add_meas_args({"ab"}),
                    "time(t)",
                ),
                primary_vars=("p", "i"),
                extra_vars=self._extra_measurement_variables({"ab"}),
                break_lines=self._cc_break_lines(step, current_ma),
            ),
        ]

    def _render_cv(self, step: _core.ConstantVoltage) -> list[str]:
        run_time_s = step.until_time_s or self._fallback_runtime_s()
        return [
            "# Constant voltage",
            "cell_off",
            "set_pgstat_mode 2",
            f"# Hold {self._ms_float(step.voltage_V)} V and measure every "
            f"{self._ms_float(self.protocol.record.time_s)} s for up to "
            f"{self._ms_float(run_time_s)} s.",
            (
                f"set_range_minmax da {self._ms_float(step.voltage_V)} "
                f"{self._ms_float(step.voltage_V)}"
            ),
            f"set_e {self._ms_float(step.voltage_V)}",
            "cell_on",
            self._measurement_loop(
                self._command_with_optional_args(
                    f"meas_loop_ca p i {self._ms_float(step.voltage_V)} "
                    f"{self._ms_float(self.protocol.record.time_s)} "
                    f"{self._ms_float(run_time_s)}",
                    self._add_meas_args({"ba"}),
                    "time(t)",
                ),
                primary_vars=("p", "i"),
                extra_vars=self._extra_measurement_variables({"ba"}),
                break_lines=self._cv_break_lines(step),
            ),
        ]

    def _render_lsv(self, step: _core.VoltageScan) -> list[str]:
        step_voltage = self.scan_step_voltage_v or self.protocol.record.voltage_V
        assert step_voltage is not None  # noqa: S101
        return [
            "# Linear sweep voltammetry",
            "cell_off",
            "set_pgstat_mode 2",
            f"# Sweep from {self._ms_float(step.start_voltage_V)} V to "
            f"{self._ms_float(step.end_voltage_V)} V in {self._ms_float(abs(step_voltage))} V "
            f"steps at {self._ms_float(step.scan_rate_mV_per_s / 1000)} V/s.",
            "cell_on",
            self._measurement_loop(
                self._command_with_optional_args(
                    f"meas_loop_lsv p i {self._ms_float(step.start_voltage_V)} "
                    f"{self._ms_float(step.end_voltage_V)} {self._ms_float(abs(step_voltage))} "
                    f"{self._ms_float(step.scan_rate_mV_per_s / 1000)}",
                    self._add_meas_args({"ba"}),
                    "time(t)",
                ),
                primary_vars=("p", "i"),
                extra_vars=self._extra_measurement_variables({"ba"}),
            ),
        ]

    def _render_eis(self, step: _core.ImpedanceSpectroscopy) -> list[str]:
        points = self._eis_point_count(step)
        if step.amplitude_V is not None:
            if step.dc_vs_ocv:
                return [
                    "# Potentiostatic EIS",
                    "cell_off",
                    "set_pgstat_mode 3",
                    "meas_loop_ocp ocp1 200m 1",
                    "endloop",
                    "store_var v_ocp1 10 ab",
                    "add_var v_ocp1 ocp1",
                    "set_e v_ocp1",
                    "cell_on",
                    self._measurement_loop(
                        f"meas_loop_eis f z_real z_imag {self._ms_float(step.amplitude_V)} "
                        f"{self._ms_float(step.start_frequency_Hz)} "
                        f"{self._ms_float(step.end_frequency_Hz)} {points}i v_ocp1",
                        primary_vars=("f", "z_real", "z_imag"),
                        include_time=False,
                    ),
                ]
            return [
                "# Potentiostatic EIS",
                "cell_off",
                "set_pgstat_mode 3",
                f"# PEIS amplitude {self._ms_float(step.amplitude_V)} Vrms from "
                f"{self._ms_float(step.start_frequency_Hz)} Hz to "
                f"{self._ms_float(step.end_frequency_Hz)} Hz with {points} points.",
                "cell_on",
                self._measurement_loop(
                    f"meas_loop_eis f z_real z_imag {self._ms_float(step.amplitude_V)} "
                    f"{self._ms_float(step.start_frequency_Hz)} "
                    f"{self._ms_float(step.end_frequency_Hz)} {points}i "
                    f"{self._ms_float(step.dc_potential_V or 0.0)} "
                    "eis_acdc(e_ac e_dc i_ac i_dc) time(t)",
                    primary_vars=("f", "z_real", "z_imag", "e_ac", "e_dc", "i_ac", "i_dc"),
                ),
            ]
        assert step.amplitude_mA is not None  # noqa: S101
        return [
            "# Galvanostatic EIS",
            "cell_off",
            "set_pgstat_mode 6",
            f"# GEIS amplitude {self._ms_float(step.amplitude_mA / 1000)} Arms from "
            f"{self._ms_float(step.start_frequency_Hz)} Hz to "
            f"{self._ms_float(step.end_frequency_Hz)} Hz with {points} points.",
            "cell_on",
            self._measurement_loop(
                f"meas_loop_geis f z_real z_imag {self._ms_float(step.amplitude_mA / 1000)} "
                f"{self._ms_float(step.start_frequency_Hz)} "
                f"{self._ms_float(step.end_frequency_Hz)} {points}i "
                f"{self._ms_float((step.dc_current_mA or 0.0) / 1000)} "
                "eis_acdc(e_ac e_dc i_ac i_dc) time(t)",
                primary_vars=("f", "z_real", "z_imag", "e_ac", "e_dc", "i_ac", "i_dc"),
            ),
        ]

    def _measurement_loop(
        self,
        command: str,
        primary_vars: tuple[str, ...],
        extra_vars: tuple[MeasurementVariable, ...] = (),
        break_lines: list[str] | None = None,
        include_time: bool = True,
    ) -> str:
        body = [
            "pck_start",
            *( ["pck_add t"] if include_time else [] ),
            *(f"pck_add {var}" for var in primary_vars),
            *(f"pck_add {self._var_name(var.var_type)}" for var in extra_vars),
            "pck_end",
            *(break_lines or []),
            "endloop",
        ]
        return "\n".join([command, *self._indent(body)])

    def _add_meas_args(self, primary_var_types: set[str]) -> str:
        args = [
            f"add_meas({self.channel} {var.var_type} {self._var_name(var.var_type)})"
            for var in self._extra_measurement_variables(primary_var_types)
        ]
        return " ".join(args)

    def _command_with_optional_args(self, command: str, *optional_args: str) -> str:
        return " ".join(arg for arg in (command, *optional_args) if arg)

    def _extra_measurement_variables(
        self,
        primary_var_types: set[str],
    ) -> tuple[MeasurementVariable, ...]:
        return tuple(
            var
            for var in self._additional_measurement_variables()
            if var.var_type not in primary_var_types
        )

    def _additional_measurement_variables(self) -> tuple[MeasurementVariable, ...]:
        requested = set(self.additional_measurements)
        return tuple(var for var in self.profile.measurement_variables if var.var_type in requested)

    def _cc_break_lines(self, step: _core.ConstantCurrent, current_ma: float) -> list[str]:
        if step.until_voltage_V is None:
            return []
        op = ">=" if current_ma > 0 else "<="
        return [
            f"# Stop when measured potential is {op} {self._ms_float(step.until_voltage_V)} V.",
            f"if p {op} {self._ms_float(step.until_voltage_V)}",
            "  breakloop",
            "endif",
        ]

    def _cv_break_lines(self, step: _core.ConstantVoltage) -> list[str]:
        until_ma = self._cv_until_current_ma(step)
        if until_ma is None:
            return []
        threshold = self._ms_float(abs(until_ma) / 1000)
        return [
            f"# Stop when measured current magnitude is <= {threshold} A.",
            f"if i <= {threshold}",
            "  if i >= " + self._ms_float(-abs(until_ma) / 1000),
            "    breakloop",
            "  endif",
            "endif",
        ]

    def _step_current_ma(self, step: _core.ConstantCurrent) -> float:
        if step.rate_C is not None and self.protocol.sample.capacity_mAh:
            return step.rate_C * self.protocol.sample.capacity_mAh
        assert step.current_mA is not None  # noqa: S101
        return step.current_mA

    def _cv_until_current_ma(self, step: _core.ConstantVoltage) -> float | None:
        if step.until_rate_C is not None and self.protocol.sample.capacity_mAh:
            return step.until_rate_C * self.protocol.sample.capacity_mAh
        return step.until_current_mA

    def _eis_point_count(self, step: _core.ImpedanceSpectroscopy) -> int:
        decades = abs(math.log10(step.start_frequency_Hz) - math.log10(step.end_frequency_Hz))
        return max(2, math.floor(decades * step.points_per_decade) + 1)

    def _fallback_runtime_s(self) -> float:
        return 2_147_000.0

    def _var_name(self, var_type: str) -> str:
        return f"meas_{var_type}"

    def _ms_float(self, value: float) -> str:
        decimal_value = Decimal(str(value))
        if decimal_value == 0:
            return "0"
        if decimal_value == decimal_value.to_integral_value():
            return f"{decimal_value:.0f}"
        factors = (
            (Decimal("1e9"), "G"),
            (Decimal("1e6"), "M"),
            (Decimal("1e3"), "k"),
            (Decimal("1e-3"), "m"),
            (Decimal("1e-6"), "u"),
            (Decimal("1e-9"), "n"),
            (Decimal("1e-12"), "p"),
        )
        for factor, suffix in factors:
            scaled = decimal_value / factor
            if scaled == scaled.to_integral_value() and abs(scaled) >= 1:
                return f"{scaled:.0f}{suffix}"
        scaled = (decimal_value / Decimal("1e-12")).quantize(Decimal(1), rounding=ROUND_HALF_UP)
        return f"{scaled:.0f}p"

    def _indent(self, lines: list[str]) -> list[str]:
        return [f"  {line}" if line else line for line in lines]


def to_palmsens_methodscript(  # noqa: PLR0913
    protocol: _core.BaseProtocol,
    save_path: Path | str | None = None,
    sample_name: str | None = None,
    capacity_mAh: float | None = None,  # noqa: N803
    device: PalmSensDevice | str = PalmSensDevice.EMSTAT4_HR,
    channel: int = 0,
    scan_step_voltage_V: float | None = None,  # noqa: N803
    additional_measurements: tuple[str, ...] = (),
) -> str:
    """Convert protocol to PalmSens MethodSCRIPT."""
    protocol = protocol.model_copy(deep=True)
    if sample_name:
        protocol.sample.name = sample_name
    if capacity_mAh:
        protocol.sample.capacity_mAh = capacity_mAh

    profile = _normalize_profile(device)

    _utils.validate_capacity_c_rates(protocol)
    _utils.tag_to_indices(protocol)
    _utils.check_for_intersecting_loops(protocol)
    _validate_common(protocol, profile, channel, scan_step_voltage_V)
    additional_measurements = _normalize_additional_measurements(additional_measurements, profile)

    renderer = _Renderer(
        protocol=protocol,
        profile=profile,
        channel=channel,
        scan_step_voltage_v=scan_step_voltage_V,
        additional_measurements=additional_measurements,
    )
    methodscript = "\n".join(renderer.render())

    if save_path:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        with save_path.open("w", encoding="utf-8") as f:
            f.write(methodscript)

    return methodscript


def _normalize_profile(device: PalmSensDevice | str) -> PalmSensProfile:
    try:
        normalized = PalmSensDevice(device)
    except ValueError as exc:
        msg = (
            f"Unsupported PalmSens device {device!r}. "
            "Supported devices are emstat4_hr, emstat4_lr, and nexus. "
            "EmStat Pico and Sensit are not supported for battery cycling because "
            "they do not support the required galvanostatic MethodSCRIPT commands."
        )
        raise ValueError(msg) from exc
    return PALMSENS_PROFILES[normalized]


def _normalize_additional_measurements(
    additional_measurements: tuple[str, ...],
    profile: PalmSensProfile,
) -> tuple[str, ...]:
    supported = {var.var_type for var in profile.measurement_variables}
    normalized = tuple(dict.fromkeys(additional_measurements))
    unsupported = sorted(set(normalized) - supported)
    if unsupported:
        msg = (
            f"Unsupported additional PalmSens measurement variable(s) for "
            f"{profile.display_name}: {', '.join(unsupported)}. "
            f"Supported values are: {', '.join(sorted(supported))}."
        )
        raise ValueError(msg)
    return normalized


def _validate_common(  # noqa: C901, PLR0912
    protocol: _core.BaseProtocol,
    profile: PalmSensProfile,
    channel: int,
    scan_step_voltage_v: float | None,
) -> None:
    if channel < 0:
        msg = "PalmSens channel must be zero or a positive integer."
        raise ValueError(msg)
    if protocol.record.time_s is None or protocol.record.time_s <= 0:
        msg = "PalmSens MethodSCRIPT export requires record.time_s."
        raise ValueError(msg)
    for step in protocol.method:
        match step:
            case _core.OpenCircuitVoltage():
                pass
            case _core.ConstantCurrent():
                _validate_current(_constant_current_ma(step, protocol), profile)
                if step.until_voltage_V is not None:
                    _validate_voltage(step.until_voltage_V, profile)
            case _core.ConstantVoltage():
                _validate_voltage(step.voltage_V, profile)
                until_current_ma = _constant_voltage_until_ma(step, protocol)
                if until_current_ma is not None:
                    _validate_current(until_current_ma, profile)
            case _core.VoltageScan():
                _validate_voltage(step.start_voltage_V, profile)
                _validate_voltage(step.end_voltage_V, profile)
                if scan_step_voltage_v is None and protocol.record.voltage_V is None:
                    msg = "PalmSens VoltageScan requires scan_step_voltage_V or record.voltage_V."
                    raise ValueError(msg)
            case _core.ImpedanceSpectroscopy():
                _validate_eis(step, profile)
            case _core.Loop() | _core.Tag():
                pass
            case _:
                msg = f"to_palmsens_methodscript() does not support step type: {step.step}"
                raise NotImplementedError(msg)


def _validate_voltage(voltage_v: float, profile: PalmSensProfile) -> None:
    if not profile.min_voltage_v <= voltage_v <= profile.max_voltage_v:
        msg = (
            f"Voltage {voltage_v} V is outside the {profile.display_name} range "
            f"({profile.min_voltage_v} to {profile.max_voltage_v} V)."
        )
        raise ValueError(msg)


def _validate_current(current_ma: float, profile: PalmSensProfile) -> None:
    if abs(current_ma) > profile.max_abs_current_ma:
        msg = (
            f"Current {current_ma} mA is outside the {profile.display_name} range "
            f"(+/-{profile.max_abs_current_ma} mA)."
        )
        raise ValueError(msg)


def _validate_eis(step: _core.ImpedanceSpectroscopy, profile: PalmSensProfile) -> None:
    max_frequency = max(step.start_frequency_Hz, step.end_frequency_Hz)
    if step.amplitude_V is not None:
        if abs(step.amplitude_V) > profile.max_peis_amplitude_v:
            msg = (
                f"PEIS amplitude {step.amplitude_V} V is outside the {profile.display_name} "
                f"limit ({profile.max_peis_amplitude_v} V)."
            )
            raise ValueError(msg)
        if max_frequency > profile.max_peis_frequency_hz:
            msg = (
                f"PEIS frequency {max_frequency} Hz is outside the {profile.display_name} "
                f"limit ({profile.max_peis_frequency_hz} Hz)."
            )
            raise ValueError(msg)
        if not step.dc_vs_ocv:
            _validate_voltage(step.dc_potential_V or 0.0, profile)
    else:
        assert step.amplitude_mA is not None  # noqa: S101
        if not profile.supports_geis:
            msg = f"{profile.display_name} does not support GEIS export."
            raise ValueError(msg)
        _validate_current(step.amplitude_mA, profile)
        if max_frequency > profile.max_geis_frequency_hz:
            msg = (
                f"GEIS frequency {max_frequency} Hz is outside the {profile.display_name} "
                f"limit ({profile.max_geis_frequency_hz} Hz)."
            )
            raise ValueError(msg)
        if step.dc_vs_ocv:
            raise ValueError("OCV-referenced DC mode is only supported for PEIS.")
        _validate_current(step.dc_current_mA or 0.0, profile)


def _constant_current_ma(step: _core.ConstantCurrent, protocol: _core.BaseProtocol) -> float:
    if step.rate_C is not None:
        if not protocol.sample.capacity_mAh:
            msg = "Sample capacity must be set if using C-rate steps."
            raise ValueError(msg)
        return step.rate_C * protocol.sample.capacity_mAh
    assert step.current_mA is not None  # noqa: S101
    return step.current_mA


def _constant_voltage_until_ma(
    step: _core.ConstantVoltage,
    protocol: _core.BaseProtocol,
) -> float | None:
    if step.until_rate_C is not None and protocol.sample.capacity_mAh:
        return step.until_rate_C * protocol.sample.capacity_mAh
    return step.until_current_mA
